FROM golang:latest

RUN mkdir /app
WORKDIR /app

# RUN mkdir /go/pkg/mod/camission


# RUN apk add --no-cache \
#     alpine-sdk \
#     git \
RUN go mod init \
    && go get github.com/pilu/fresh \
    && go get -u github.com/gorilla/mux \
    && go get -u github.com/go-sql-driver/mysql \
    && go get -u github.com/jinzhu/gorm \
    && go get -u github.com/go-playground/validator \
    && go get -u github.com/google/uuid